### PR TITLE
Feature/routing

### PR DESCRIPTION
**Pull request by andreasgarvik**
Added some routing

### CODE REVIEW

**Comment by sondregj** [comment]
The `/api` may rather be added like so in index.js for each of the routers for a bit more modularity.

```javascript
app // Routes
	.use('/api/exhibitions', exhibitions)
	.use('/api/users', users)
	.use('/api/votes', votes)
```

Otherwise looking good.

**Comment by 180312** [comment]
Wrote correct url directly in routing files:
`router.get('/api/votes/', async (req, res) => {
	res.send(await VotesService.read())
})`

**Comment by arnemolland** [comment]
By the way, before merging, all requests should be sanitized to prevent SQL injection attacks

**Comment by 180312** [comment]
Node-postgres parameterized query avoid SQL injection.
Docs: https://github.com/brianc/node-postgres/wiki/FAQ

**Comment by sondregj** [comment]
Any suggestions for what test library to use?

**Review by arnemolland — APPROVED** [review]
👍

**Review by sondregj — APPROVED** [review]
Good. Closing.

**Pull request merged**
